//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvalTecUPC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SolucitudesContext : DbContext
    {
        public SolucitudesContext()
            : base("name=SolucitudesContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DETALLE_SOLICITUD> DETALLE_SOLICITUD { get; set; }
        public DbSet<SOLICITUD> SOLICITUD { get; set; }
    
        public virtual int SP_READSOLICITUDDETALLE(string cOD_LINEA_NEGOCIO_EX, string cOD_MODAL_EST_EX, string cOD_PERIODO_EX, Nullable<decimal> cOD_TRAMITE_EX, string eSTADO_EX)
        {
            var cOD_LINEA_NEGOCIO_EXParameter = cOD_LINEA_NEGOCIO_EX != null ?
                new ObjectParameter("COD_LINEA_NEGOCIO_EX", cOD_LINEA_NEGOCIO_EX) :
                new ObjectParameter("COD_LINEA_NEGOCIO_EX", typeof(string));
    
            var cOD_MODAL_EST_EXParameter = cOD_MODAL_EST_EX != null ?
                new ObjectParameter("COD_MODAL_EST_EX", cOD_MODAL_EST_EX) :
                new ObjectParameter("COD_MODAL_EST_EX", typeof(string));
    
            var cOD_PERIODO_EXParameter = cOD_PERIODO_EX != null ?
                new ObjectParameter("COD_PERIODO_EX", cOD_PERIODO_EX) :
                new ObjectParameter("COD_PERIODO_EX", typeof(string));
    
            var cOD_TRAMITE_EXParameter = cOD_TRAMITE_EX.HasValue ?
                new ObjectParameter("COD_TRAMITE_EX", cOD_TRAMITE_EX) :
                new ObjectParameter("COD_TRAMITE_EX", typeof(decimal));
    
            var eSTADO_EXParameter = eSTADO_EX != null ?
                new ObjectParameter("ESTADO_EX", eSTADO_EX) :
                new ObjectParameter("ESTADO_EX", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_READSOLICITUDDETALLE", cOD_LINEA_NEGOCIO_EXParameter, cOD_MODAL_EST_EXParameter, cOD_PERIODO_EXParameter, cOD_TRAMITE_EXParameter, eSTADO_EXParameter);
        }
    }
}
