//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvalTecUPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_SOLICITUD
    {
        public long COD_DETALLE { get; set; }
        public string COD_CURSO { get; set; }
        public string COD_TIPO_PRUEBA { get; set; }
        public Nullable<short> NUM_PRUEBA { get; set; }
        public string SECCION { get; set; }
        public string GRUPO { get; set; }
        public string ESTADO_CURSO { get; set; }
        public long COD_UNICO { get; set; }
    
        public virtual SOLICITUD SOLICITUD { get; set; }
    }
}
