//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvalTecUPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        public SOLICITUD()
        {
            this.DETALLE_SOLICITUD = new HashSet<DETALLE_SOLICITUD>();
        }
    
        public string COD_LINEA_NEGOCIO { get; set; }
        public string COD_MODAL_EST { get; set; }
        public string COD_PERIODO { get; set; }
        public Nullable<short> COD_TRAMITE { get; set; }
        public long COD_UNICO { get; set; }
        public string ESTADO { get; set; }
        public string COD_ALUMNO { get; set; }
    
        public virtual ICollection<DETALLE_SOLICITUD> DETALLE_SOLICITUD { get; set; }
    }
}
